[package]
name = "marsc_resolve"
version = "0.1.0"
edition = "2021"

[dependencies]
marsc_context = { path = "../marsc_context" }
marsc_hir = { path = "../marsc_hir" }
uuid = { version = "1.11.0", features = ["v4"] }
