[package]
name = "mars-lang"
version = "0.1.0"
edition = "2021"
license = "BSDv3"
description = """
Mars programming language compiler entry point
"""

[[bin]]
name = "mars"
path = "src/main.rs"

[dependencies]

[workspace]
resolver = "2"
members = [
    "compiler/marsc",
    "compiler/marsc_codegen",
    "compiler/marsc_context",
    "compiler/marsc_core",
    "compiler/marsc_data_structures",
    "compiler/marsc_driver",
    "compiler/marsc_hir",
    "compiler/marsc_session",
    "compiler/marsc_query_system",
    "compiler/marsc_proc_macro",
    "compiler/marsc_resolve",
]