[workspace]
resolver = "2"
members = [
    "compiler/marsc",
    "compiler/marsc_codegen",
    "compiler/marsc_context",
    "compiler/marsc_core",
    "compiler/marsc_data_structures",
    "compiler/marsc_hir",
    "compiler/marsc_session",
    "compiler/marsc_query_system",
    "compiler/marsc_proc_macro",
]
