[package]
name = "marsc_code_span"
version = "0.1.0"
edition = "2021"
license = "BSDv3"
description = """
Mars source code span compiler module used by marsc
"""

[lib]
name = "marsc_span"
path = "src/lib.rs"

[dependencies]
