[package]
name = "marsc_lexer"
version = "0.1.0"
edition = "2021"
license = "BSDv3"
description = """
Mars lexer used by marsc
"""

[lib]
path = "src/lib.rs"
name = "m_lex"

[dependencies]
marsc_code_span = { path = "../marsc_code_span" }