[package]
name = "marsc_ast"
version = "0.1.0"
edition = "2021"
license = "BSDv3"
description = """
Mars programming language compiler ast
"""

[lib]
name = "ast"
path = "src/lib.rs"

[dependencies]
pest = "2.7.14"